name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  build:
    name: "Builds"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Run builds
        run: pnpm run build
        env:
          CI_OS: ${{ runner.os }}

  check:
    timeout-minutes: 30
    name: "Checks"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: ["build"]
    steps:
      - name: Checkout Repo
        if: ${{ steps.cache-repo.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Check for errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          CI_OS: ${{ matrix.os }}

      - name: Check the changesets
        run: node -r esbuild-register tools/deployments/validate-changesets.ts

  check-non-linux:
    if: github.head_ref == 'changeset-release/main'
    timeout-minutes: 30
    name: "Checks"
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        if: ${{ steps.cache-repo.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Check for errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          CI_OS: ${{ matrix.os }}

      - name: Check the changesets
        run: node -r esbuild-register tools/deployments/validate-changesets.ts

  test:
    timeout-minutes: 30
    needs: ["build"]

    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        filter:
          [
            '--filter="./packages/*" --filter="./fixtures/*" --filter="./packages/vite-plugin-cloudflare/playground"',
          ]
        # Things in the tools folder are for running in CI, and so only need to run on linux
        include:
          - os: ubuntu-latest
            filter: '--filter="./tools"'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        if: ${{ steps.cache-repo.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Run tests
        run: pnpm run test:ci --concurrency 1 ${{ matrix.filter }}
        env:
          TMP_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TMP_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_OPTIONS: "--max_old_space_size=8192"
          WRANGLER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
          TEST_REPORT_PATH: ${{ runner.temp }}/test-report/index.html
          CI_OS: ${{ runner.os }}
