name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  build:
    name: "Builds"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: node_modules
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: ${{ github.sha }}-${{ matrix.os }}-ci-cache
          path: node_modules

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Run builds
        run: pnpm run build
        env:
          CI_OS: ${{ runner.os }}

      - name: node_modules
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-${{ matrix.os }}-ci-cache
          path: node_modules
  check:
    timeout-minutes: 30
    name: "Checks"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: ["build"]
    steps:
      - name: Checkout Repo
        if: ${{ steps.cache-repo.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: node_modules
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}-${{ matrix.os }}-ci-cache
          path: node_modules

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

      - name: Check for errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          CI_OS: ${{ matrix.os }}

      - name: Check the changesets
        run: node -r esbuild-register tools/deployments/validate-changesets.ts

  check-non-linux:
    if: github.head_ref == 'changeset-release/main'
    timeout-minutes: 30
    name: "Checks"
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        if: ${{ steps.cache-repo.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache repository
        uses: actions/cache@v3
        id: cache-repo
        with:
          key: ${{ github.sha }}-${{ matrix.os }}-ci-cache
          path: |
            node_modules

      - name: Check for errors
        run: pnpm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          CI_OS: ${{ matrix.os }}

      - name: Check the changesets
        run: node -r esbuild-register tools/deployments/validate-changesets.ts
